x-variables:
  election_timeout: &election_timeout '--election-timeout=2000'
  heartbeat_interval: &heartbeat_interval '--heartbeat-interval=200'
  initial_cluster: &initial_cluster '--initial-cluster=sight_etcd_0=http://sight_etcd_0:2380'
  initial_cluster_state: &initial_cluster_state '--initial-cluster-state=new'
  initial_cluster_token: &initial_cluster_token '--initial-cluster-token=secrettoken'
  listen_peer_urls: &listen_peer_urls '--listen-peer-urls=http://0.0.0.0:2380'
  listen_client_urls: &listen_client_urls '--listen-client-urls=http://0.0.0.0:2379'
  peer-trusted-ca-file: &peer-trusted-ca-file '--peer-trusted-ca-file=${HOME}/sight/certs/ca.crt'
  auto-tls: &auto-tls '--auto-tls'
  peer-auto-tls: &peer-auto-tls '--peer-auto-tls'

  common_api_settings: &common_api_settings
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 250M
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_TIMEOUT=${JWT_TIMEOUT}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_REFRESH_TIMEOUT=${JWT_REFRESH_TIMEOUT}
      - PASSWORD_SALT_ROUNDS=${PASSWORD_SALT_ROUNDS}
      - SIGHT_DB_HOSTS=${SIGHT_DB_HOSTS}
      - SIGHT_DB_USER=${SIGHT_DB_USER}
      - SIGHT_DB_PASS=${SIGHT_DB_PASS}
      - SIGHT_ETCD_HOSTS=${SIGHT_ETCD_HOSTS}
      - NODE_ENV=docker
    networks:
      api_layer:
      data_layer:
    
  common_broadcast_settings: &common_broadcast_settings
    <<: *common_api_settings
    image: 'sight_broadcast_img'
    build:
      context: .
      dockerfile: ./backend/broadcast/Dockerfile
    ports:
      - '1000'

  common_gateway_settings: &common_gateway_settings
    <<: *common_api_settings
    image: 'sight_gateway_img'
    build:
      context: .
      dockerfile: ./backend/gateway/Dockerfile
    ports:
      - '1234'

services:
  sight_io_proxy: 
    image: sight_proxy_img
    container_name: sight_io_proxy
    hostname: ${HOSTNAME}
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 250M
    build:
      context: .
      dockerfile: ./lb/Dockerfile.io
    volumes:
      - $HOME/sight/certs/haproxy:/certs
      - $HOME/sight/sight_io_proxy/log:/var/log/haproxy
    ports: 
      - '443:443'
    networks:
      api_layer:
      data_layer:
  sight_broadcast_0:
    <<: *common_broadcast_settings
    hostname: sight_broadcast_0
    container_name: sight_broadcast_0
  sight_gateway_0:
    <<: *common_gateway_settings
    hostname: sight_gateway_0
    container_name: sight_gateway_0

networks:
  api_layer:
    driver: bridge
  data_layer:
    driver: bridge